image_dir: ./data/images_vision_1920x1080
output_dir: ./output

image_width: 1920
image_height: 1080
resize: null

vanish_line: 667 # 消失线
world_width: 30 # IPM中真实距离x方向[-15, 15], 单位：m
world_height: 20 # IPM中真实距离y方向[0, 20], 单位：m
world_pixel: 0.04 # 像素点真实距离，单位: m
world_y_start: 5.0 # 单位: m

# 畸变参数k1 k2 p1 p2 [k3, [k4, k5, k6]]
distort: [-0.077837, -0.060080, -0.001426, 0.006125, 0.050293, 0.082630, 0.065548, -0.048917]

# 相机内参fx fy cx cy
intrinsic: [1070.3158, 1118.2645, 961.0000, 542.0000]

# 相机外参world2camera 车头坐标系（右前上）-> 相机坐标系（右下前）
Rwc: [0.997440755, -0.0714974478, 0.00000000,
      0.00794494059, 0.110837631, -0.993806779,
      0.0710546449, 0.991263390, 0.111122020]
Twc: [-0.00000000, 1.25319031, -0.140124863]
