image_dir: ./data/images_csmp_960x540
output_dir: ./output

image_width: 960
image_height: 540
resize: null

vanish_line: 280 # 消失线
world_width: 30 # IPM中真实距离x方向[-15, 15], 单位：m
world_height: 8 # IPM中真实距离y方向[0, 8], 单位：m
world_pixel: 0.04 # 像素点真实距离，单位: m
world_y_start: 3.0 # 单位: m

# 畸变参数k1 k2 p1 p2 [k3, [k4, k5, k6]]
distort: [0.0, 0.0, 0.0, 0.0]

# 相机内参fx fy cx cy
intrinsic: [476.2483, 477.0686, 484.8964, 262.8846]

# 相机外参world2camera 车头坐标系（右前上）-> 相机坐标系（右下前）
Rwc: [0.9937560081539198, 0.1109831719351175, 0.01147744767823091,
      0.003276455792956701, 0.07379581423704455, -0.9972679893782455,
      -0.111526952327333, 0.9910786615341447, 0.07297140231806608]
Twc: [0.2317971025971608, 1.713913045205863, 1.913995241236965]