image_dir: /home/zwx/work/misc/IPM/images/ptz
output_dir: ./output

image_width: 2560
image_height: 1440
resize: null

vanish_line: 720 # 消失线, 单位: 像素
world_width: 20 # IPM中x方向真实距离[-10, 10], 单位: m
world_height: 20 # IPM中y方向真实距离[-10, 10], 单位: m
world_pixel: 0.01 # 像素点真实距离，单位: m
world_y_start: 0.0 # 单位: m

# 畸变系数k1 k2 p1 p2 [k3, [k4, k5, k6]]
distort: [-0.3171263470212019, 0.08404949178840937, -0.001337755505090682, 0.00665465641809741]

# 相机内参fx fy cx cy
intrinsic: [1945.9191092565568, 1694.0721244890497, 1280.0, 720.0]

# 相机外参, 世界坐标系（右前上）到相机坐标系（右下前）
Rcw: [-0.009336205092904705, -0.9999343156030109, -0.006648289554526738,
      -0.11226739814194366, 0.007654717511244498, -0.993648547834827,
      0.9936341714076168, -0.008530520462471663, -0.11233148993820877]
tcw: [-0.07230302078704648, 1.023733163682915,0.4105864288475217]
